### ISSUE TITLE
Questions about the implementation for inner loop

### ISSUE THREAD

**Issue by hytseng0509** [katerakelly/pytorch-maml#11]
Hi,

Thanks for sharing the code. I have questions about the implementation for [inner loop](https://github.com/katerakelly/pytorch-maml/blob/f4d36caa4cdd43d28332befaf88b4df8551c0f34/src/inner_loop.py#L57):
Is there any reason for the special case of `i == 0`? Can we just use `fast_weights` for `i == 0`?

Thanks!

**Comment by hytseng0509** [comment]
Thanks for the explanation!

**Comment by frajem** [comment]
Hi, 
sorry to reopen this discussion. As you define the fast_weights to be same as the original weights, in here (https://github.com/katerakelly/pytorch-maml/blob/f4d36caa4cdd43d28332befaf88b4df8551c0f34/src/inner_loop.py#L53):
```
fast_weights = OrderedDict((name, param) for (name, param) in self.named_parameters())
for i in range(self.num_updates):
```
then there should already be a "pointer" to the original model parameters for computing the meta gradient. Thus, there should be no need to distinguish i==0. Do you think my observation is correct? 
Thanks.
