### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by hughperkins** [katerakelly/pytorch-maml#12]
Hi, Amazing repo and implementation :)

Please can you confirm what license this code is released under?

**Comment by dendisuhubdy** [comment]
https://github.com/katerakelly/pytorch-maml/blob/master/LICENSE 

MIT I assume?

**Comment by hughperkins** [comment]
Good point. Note that that is dated 9 days ago ;)  :

<img width="999" alt="screen shot 2018-10-13 at 8 27 35 pm" src="https://user-images.githubusercontent.com/123560/46911332-75641400-cf26-11e8-8c8a-a286fc2dab37.png">

Thank you @katerakelly  :)
