### ISSUE TITLE
Hi, how to evaluate light version?(without high order gradients)

### ISSUE THREAD

**Issue by XiongweiWu** [katerakelly/pytorch-maml#14]

**Comment by katerakelly** [comment]
Sorry, this isn't implemented currently.

**Comment by XiongweiWu** [comment]
@katerakelly I wonder whether u can set create_graph=False(https://github.com/katerakelly/pytorch-maml/blob/75907aca148ad053dfaf75fc138319f0d89534a8/src/inner_loop.py#L62 and https://github.com/katerakelly/pytorch-maml/blob/75907aca148ad053dfaf75fc138319f0d89534a8/src/inner_loop.py#L59) and test the result? Since I got similar results with this setting
