### ISSUE TITLE
Hessian-vector products

### ISSUE THREAD

**Issue by buaaswf** [katerakelly/pytorch-maml#17]
In the original paper, the authors claimed that MAML needs second gradient and Hessian-vector products. Could you explain how do you implement this or Pytorch just do this automatically? Thanks!
referenced https://github.com/dragen1860/MAML-Pytorch/issues/18

**Comment by katerakelly** [comment]
PyTorch can compute the second derivatives automatically. See these lines for how it's done in this codebase: https://github.com/katerakelly/pytorch-maml/blob/master/src/inner_loop.py#L53-L77
