### ISSUE TITLE
result on mini-imagenet dataset

### ISSUE THREAD

**Issue by kailigo** [katerakelly/pytorch-maml#7]
Hi, thanks for the code.

I am trying test the code on the mini-imagenet dataset. However, my result is very bad, much worse than the reported ones. I wonder if you have tested the implementation on the dataset, and how about your results. If possible, could you possible upload your scripts of experimenting on the mini-imagenet dataset. Your help is much appreciated.

**Comment by katerakelly** [comment]
I have not tested the implementation on miniImageNet, sorry!
